Module MOD_CONST
    Public STR_TXT_DB_DRIVER_NAME As String = "Driver={Microsoft Text Driver (*.txt; *.csv)};DBQ="
    Public STR_TXT_DB_DRIVER_INI_NAME As String = "schema.ini"

    Public Const cstVB_DATE_MIN As DateTime = #1/1/1753# 'DateTimePicker上の最小日付≒VBコード上で扱いうる最小日付(基本的に日付型のエラートラップに使用する)
    Public Const cstVB_DATE_MAX As DateTime = #12/31/9998# 'DateTimePicker上の最大日付≒VBコード上で扱いうる最大日付(基本的に永久に到達しない日付型として使用する)
    'Public Const cstvbCrlf As String = Environment.NewLine

#Region "config関連"
    Public Const CST_CONFIG_GAMEPAD_ID_GAMEPAD As String = "GAMEPAD_ID_GAMEPAD"
    Public Const CST_CONFIG_GAMEPAD_KIND_GAMEPAD As String = "GAMEPAD_KIND_GAMEPAD"

    Public Const CST_CONFIG_GAMEPAD_ALLOCATION As String = "GAMEPAD_ALLOCATION"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_BUTTON_01 As String = "BUTTON_01"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_BUTTON_02 As String = "BUTTON_02"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_BUTTON_03 As String = "BUTTON_03"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_KIND As String = "KIND"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_KEY_01 As String = "KEY_01"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_KEY_02 As String = "KEY_02"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_MOUSE_X As String = "MOUSE_X"
    Public Const CST_CONFIG_GAMEPAD_ALLOCATION_MOUSE_Y As String = "MOUSE_Y"

    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_01_BUTTON_01 As String = "GAMEPAD_ALLOCATION_01_BUTTON_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_01_BUTTON_02 As String = "GAMEPAD_ALLOCATION_01_BUTTON_02"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_01_KEY_01 As String = "GAMEPAD_ALLOCATION_01_KEY_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_01_KEY_02 As String = "GAMEPAD_ALLOCATION_01_KEY_02"

    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_02_BUTTON_01 As String = "GAMEPAD_ALLOCATION_02_BUTTON_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_02_BUTTON_02 As String = "GAMEPAD_ALLOCATION_02_BUTTON_02"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_02_KEY_01 As String = "GAMEPAD_ALLOCATION_02_KEY_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_02_KEY_02 As String = "GAMEPAD_ALLOCATION_02_KEY_02"

    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_03_BUTTON_01 As String = "GAMEPAD_ALLOCATION_03_BUTTON_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_03_BUTTON_02 As String = "GAMEPAD_ALLOCATION_03_BUTTON_02"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_03_KEY_01 As String = "GAMEPAD_ALLOCATION_03_KEY_01"
    'Public Const CST_CONFIG_GAMEPAD_ALLOCATION_03_KEY_02 As String = "GAMEPAD_ALLOCATION_03_KEY_02"

#End Region

End Module
